### ISSUE TITLE
IMDB builder imdb_search error: KeyError: 'data'

### ISSUE THREAD

**Issue by ghost** [meisnate12/Plex-Meta-Manager#1871]
### Version Number

1.20.0-nightly29 (Docker)

### What branch are you on?

nightly

### Describe the Bug

The following error happens when trying to use imdb_search:

```
|============================ Running Top Rated of the 1990s Collection =============================|
|                                                                                                    |
| Sync Mode: sync                                                                                    |
|                                                                                                    |
| Builder: imdb_search: {'limit': 500, 'language': ['en'], 'release.after': '1990-01-01', 'release.before': '1999-12-31', 'sort_by': 'rating.desc', 'type': ['tv_series', 'tv_mini_series', 'tv_special'], 'votes.gte': 100} |
|                                                                                                    |
| Processing IMDb Search:                                                                            |
|     limit: 500                                                                                     |
|     language: ['en']                                                                               |
|     release.after: 1990-01-01                                                                      |
|     release.before: 1999-12-31                                                                     |
|     sort_by: rating.desc                                                                           |
|     type: ['tv_series', 'tv_mini_series', 'tv_special']                                            |
|     votes.gte: 100                                                                                 |
| Starting new HTTPS connection (1): api.graphql.imdb.com:443                                        |
| https://api.graphql.imdb.com:443 "POST / HTTP/1.1" 200 100                                         |
| Traceback (most recent call last):                                                                 |
|   File "//plex_meta_manager.py", line 775, in run_collection                                       |
|     builder.filter_and_save_items(builder.gather_ids(method, value))                               |
|                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                |
|   File "/modules/builder.py", line 2209, in gather_ids                                             |
|     ids = self.config.IMDb.get_imdb_ids(method, value, self.language)                              |
|           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              |
|   File "/modules/imdb.py", line 572, in get_imdb_ids                                               |
|     return [(_i, "imdb") for _i in self._search(data)]                                             |
|                                    ^^^^^^^^^^^^^^^^^^                                              |
|   File "/modules/imdb.py", line 416, in _search                                                    |
|     total = response_json["data"]["advancedTitleSearch"]["total"]                                  |
|             ~~~~~~~~~~~~~^^^^^^^^                                                                  |
| KeyError: 'data'                                                                                   |
|                                                                                                    |
| Unknown Error: 'data'                                                                              |
|                                                                                                    |
|====================================================================================================|
```

### Relevant Collection/Overlay/Playlist Definition

```yml
## 0_debug.yml

templates:
  decade_top:
    collection_mode: hide
    collection_order: custom
    delete_not_scheduled: false
    limit: 250
    sort_title: "+3_<<num>>_<<collection_name>>"
    sync_mode: sync
    visible_home: false
    visible_library: false
    visible_shared: false
    imdb_search:
      language: <<language>>
      limit: 500
      release.after: <<release.after>>
      release.before: <<release.before>>
      sort_by: rating.desc
      type: <<type>>
      votes.gte: <<votes.gte>>

collections:
  "Top Rated of the 1990s":
    summary: "Top rated TV shows of the 1990s"
    file_poster: config/assets/3_decades_top/decades_top_1990s.png
    template: {
                    name: decade_top,
                    num: "T",
                    type: "tv_series,tv_mini_series,tv_special",
                    release.after: 1990-01-01,
                    release.before: 1999-12-31,
                    votes.gte: 100,
                    language: "en"
                    }
```

**Comment by YozoraXCII** [comment]
I ran your exact YAML and had no issues:

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/2b995ba5-17e9-4ac2-9df1-9ae182a6abec)

**Comment by ghost** [comment]
> I ran your exact YAML and had no issues:
> 
> ![image](https://private-user-images.githubusercontent.com/96386153/302619007-2b995ba5-17e9-4ac2-9df1-9ae182a6abec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMjE5ODAsIm5iZiI6MTcwNzIyMTY4MCwicGF0aCI6Ii85NjM4NjE1My8zMDI2MTkwMDctMmI5OTViYTUtMTdlOS00YWMyLTlkZjEtOWFlMTgyYTZhYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDEyMTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMjhkMTM5YjhjN2ZmOGE2YjFhZGIyNzU0MGY3YWFmYzFmMGI0YjU0ODcwOGNkYThmYTA4Yjg1MzlmOTA5YWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FUdV9rvhKMulmnA4F88R-vhCk5O_ztv03nzFQqSgVLM)

It seems that there was an issue on IMDB's end, but it was resolved shortly after creating this.

**Comment by BelminH** [comment]
I'm also having this issue, running the latest master release (also had this issue with a quite old nightly build). Is IMDB having issues again?

EDIT: Seems to be working again now (I did not change my config, guessing IMDB was having some sort of issue)

**Comment by able-abell** [comment]
Same issue for me, running the latest master release. It worked intermittently last week, but now I only get the 'data' error.

**Comment by YozoraXCII** [comment]
We're aware of this and have a potential solution that we have some early positive testing of - keep an eye out for a nightly update as soon as we can.

**Comment by able-abell** [comment]
> We're aware of this and have a potential solution that we have some early positive testing of - keep an eye out for a nightly update as soon as we can.

Any updates on this? I'm still getting the same 'data' error, unfortunately.

**Comment by ghost** [comment]
> > We're aware of this and have a potential solution that we have some early positive testing of - keep an eye out for a nightly update as soon as we can.
> 
> Any updates on this? I'm still getting the same 'data' error, unfortunately.

The latest nightly, released yesterday, should fix this once again.

This error will most likely reappear every time that imdb hash requires updating.

**Comment by YozoraXCII** [comment]
> > > We're aware of this and have a potential solution that we have some early positive testing of - keep an eye out for a nightly update as soon as we can.
> > 
> > 
> > Any updates on this? I'm still getting the same 'data' error, unfortunately.
> 
> The latest nightly, released yesterday, should fix this once again.
> 
> This error will most likely reappear every time that imdb hash requires updating.

Just to add to this - we have deployed an interim solution in nightly that will allow us to deploy new hashes remotely without having to update nightly/PMM.

We will look towards a fully automated solution, but this will allow us to address the issue a lot quicker.

**Comment by sebastianarena** [comment]
I'm still running into this problem on the nightly :(

**Comment by YozoraXCII** [comment]
> I'm still running into this problem on the nightly :(

we'd need a log file

**Comment by sebastianarena** [comment]
The latest release is newer than the nightly, so I'm testing that right now

**Comment by sebastianarena** [comment]
The problem is fixed in 1.21.0 that was pushed a couple of hours ago, the nightly still does have the problem, I apologize for the report. Thanks everybody. Love this product.

**Comment by YozoraXCII** [comment]
> The problem is fixed in 1.21.0 that was pushed a couple of hours ago, the nightly still does have the problem, I apologize for the report. Thanks everybody. Love this product.

You appear to have a bit of a misunderstanding and I don't think you're updating your nightly on a regular basis since this was fixed in nightly 2 weeks ago.

`nightly` is promoted to `develop` which in turn gets promoted to `master` - there is no scenario where `master` is ahead of `nightly` because of this pipeline.

`nightly` will always be on-par or ahead with `master`, but never behind it.

the final 1.21 build was pushed to `nightly` 6 hours prior to it going to `master`, but the fix you need was put into nightly 2 weeks ago - I suspect you're running an old version of nightly.

You should look on the wiki at how to keep PMM up to date.

**Comment by sebastianarena** [comment]
Thanks for clarifying.
Before sending the report I pulled the latest nightly and when running that I got the error.
I even tried the nightly from linuxserver with no success.
I don't know why it still didn't work even though it was fixed 2 weeks ago.
But thanks anyways for the clarification.
